services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    ports:
      - '80:80'
